pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment {
        COURSE = "Jenkins"
        appVersion = ""
        ACC_ID = "668918190203"
        PROJECT = "dotmart"
        COMPONENT = "catalogue"
    }
    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    //This is build pipeline
    stages {
        stage('Read Version') {
            steps {
                script{
                    def packageJSON = readJSON file: 'catalogue/package.json'
                    appVersion = packageJSON.version
                    echo "app version: ${appVersion}"
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    dir('catalogue') {
                        sh 'npm install'
                    }
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
                    dir('catalogue') {
                        sh 'npm test'
                    }
                }
            }
        }
        // Here you need to select scanner tool and send the analysis to server 
        stage('SonarScan') {
               environment {
                    def scannerHome = tool 'sonar-8.0'
                }
            steps {
                script {
                    withSonarQubeEnv('sonar-server') {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }
        stage('Build Image') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                         dir('catalogue') {
                            sh """
                                aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com
                                docker build -t ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion} .
                                docker images
                                docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
                            """                    
                }       }

            }
        }
    }

    }
    post {
        always {
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo ' I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}